export const users = [
  {
    _id: '64468fb15cf0226d186e9db0',
    index: 0,
    guid: 'a07761ce-0623-4745-9b92-974ed243154b',
    isActive: false,
    balance: '$1,088.92',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Ramsey Schneider',
    gender: 'male',
    company: 'CEPRENE',
    email: 'ramseyschneider@ceprene.com',
    phone: '+1 (946) 562-2897',
    address: '861 Winthrop Street, Nash, South Dakota, 8857',
    about:
      'Reprehenderit voluptate ea deserunt qui esse duis laborum minim exercitation. Voluptate commodo quis amet eu quis occaecat quis deserunt. Consequat Lorem commodo aute excepteur adipisicing dolore consequat in enim. Ut et exercitation amet dolore sint ullamco do. Nostrud laboris esse minim reprehenderit irure non nisi sit cupidatat. Aliquip adipisicing incididunt Lorem excepteur Lorem occaecat. Sunt eiusmod veniam veniam tempor ea Lorem sint incididunt aliquip velit enim ipsum.\r\n',
    registered: '2015-10-23T05:55:04 -06:00',
    latitude: -66.297436,
    longitude: -59.409932,
    tags: ['deserunt', 'pariatur', 'enim', 'enim', 'duis', 'quis', 'id'],
    friends: [
      {
        id: 0,
        name: 'Clara Allison',
      },
      {
        id: 1,
        name: 'Estelle Henry',
      },
      {
        id: 2,
        name: 'Miranda Rodriguez',
      },
    ],
    greeting: 'Hello, Ramsey Schneider! You have 3 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '64468fb1889f70b590cb294a',
    index: 1,
    guid: '4a03b26e-bb71-4c4a-aa33-e44986fa7ff1',
    isActive: false,
    balance: '$3,489.17',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'brown',
    name: 'Betsy Kirkland',
    gender: 'female',
    company: 'QUAILCOM',
    email: 'betsykirkland@quailcom.com',
    phone: '+1 (977) 544-3275',
    address: '142 Clark Street, Elliston, Alabama, 9807',
    about:
      'Sit occaecat reprehenderit aliquip nulla qui eiusmod incididunt velit non ipsum commodo aute. Ea officia reprehenderit culpa eu. Nisi laboris sint excepteur aute in ea adipisicing id aute amet sit fugiat sit. Consectetur pariatur minim sunt nisi dolor excepteur incididunt. Quis eu commodo exercitation culpa cillum non esse. Eiusmod commodo excepteur quis quis ut incididunt anim culpa.\r\n',
    registered: '2014-03-25T10:57:02 -06:00',
    latitude: -72.008426,
    longitude: 142.070217,
    tags: [
      'consectetur',
      'ipsum',
      'cupidatat',
      'aliqua',
      'id',
      'ad',
      'adipisicing',
    ],
    friends: [
      {
        id: 0,
        name: 'Mcleod Callahan',
      },
      {
        id: 1,
        name: 'Inez Sharpe',
      },
      {
        id: 2,
        name: 'Melendez Strickland',
      },
    ],
    greeting: 'Hello, Betsy Kirkland! You have 8 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '64468fb11c765134e5a09730',
    index: 2,
    guid: 'ee8fd611-0e38-47b0-86db-0c576f23def4',
    isActive: true,
    balance: '$1,110.59',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'blue',
    name: 'Rhonda Stone',
    gender: 'female',
    company: 'ZENCO',
    email: 'rhondastone@zenco.com',
    phone: '+1 (889) 403-3385',
    address: '994 Fanchon Place, Makena, Arkansas, 3190',
    about:
      'Esse sint exercitation sunt tempor. Labore irure commodo laboris enim qui eu consequat et Lorem. Consequat Lorem exercitation do amet adipisicing sunt eu occaecat consectetur. Excepteur ut non voluptate nulla sunt. Laboris ea commodo ex labore commodo nostrud cupidatat non sit quis commodo. Pariatur minim labore irure occaecat elit tempor aliqua id adipisicing ex id commodo excepteur laboris. Est exercitation ex id consequat ullamco irure fugiat.\r\n',
    registered: '2020-09-17T08:42:32 -06:00',
    latitude: -36.975077,
    longitude: 88.54926,
    tags: ['aliqua', 'do', 'nisi', 'id', 'ullamco', 'officia', 'dolore'],
    friends: [
      {
        id: 0,
        name: 'Kristin Keller',
      },
      {
        id: 1,
        name: 'Claudia Fleming',
      },
      {
        id: 2,
        name: 'Kemp Beard',
      },
    ],
    greeting: 'Hello, Rhonda Stone! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '64468fb1495a9d8f8a2abead',
    index: 3,
    guid: '28680132-c225-4cda-84aa-3b27f96f2f44',
    isActive: false,
    balance: '$3,098.92',
    picture: 'http://placehold.it/32x32',
    age: 26,
    eyeColor: 'blue',
    name: 'Villarreal Phillips',
    gender: 'male',
    company: 'EMPIRICA',
    email: 'villarrealphillips@empirica.com',
    phone: '+1 (841) 539-3113',
    address: '482 Fenimore Street, Waverly, North Carolina, 9914',
    about:
      'Ex nulla Lorem anim minim est duis quis. Consectetur consequat consectetur incididunt pariatur aute do et ullamco veniam culpa nisi tempor consequat. Nulla anim esse aliquip commodo cupidatat eu qui voluptate nulla id nulla proident aute cupidatat. Enim laborum ipsum culpa sunt aliqua ad. In magna commodo laborum id amet anim sit labore duis occaecat aliqua.\r\n',
    registered: '2020-02-25T01:14:43 -06:00',
    latitude: -66.681316,
    longitude: 84.665116,
    tags: ['laboris', 'eu', 'ex', 'do', 'occaecat', 'veniam', 'duis'],
    friends: [
      {
        id: 0,
        name: 'King Olsen',
      },
      {
        id: 1,
        name: 'Ross Ortega',
      },
      {
        id: 2,
        name: 'Vinson Vance',
      },
    ],
    greeting: 'Hello, Villarreal Phillips! You have 3 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '64468fb1e7e3f4b5b173adfa',
    index: 4,
    guid: '0617e194-04a1-484b-b8b5-3b71295bc393',
    isActive: true,
    balance: '$2,435.33',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'blue',
    name: 'Cornelia Meadows',
    gender: 'female',
    company: 'BUNGA',
    email: 'corneliameadows@bunga.com',
    phone: '+1 (812) 563-3217',
    address: '179 Madoc Avenue, Camptown, Pennsylvania, 1348',
    about:
      'Duis elit ut magna et labore et. Aute commodo proident fugiat irure consequat fugiat nostrud aute veniam elit tempor occaecat. Ad laboris nulla excepteur Lorem aliqua laboris dolor in labore. Sit eiusmod qui velit magna ea. Sint minim nostrud ex aute ullamco cillum. Pariatur adipisicing nulla esse cupidatat ut veniam officia voluptate. Sunt cupidatat veniam qui aliquip voluptate consequat nostrud ipsum sint elit duis dolore ipsum est.\r\n',
    registered: '2020-11-05T11:44:31 -06:00',
    latitude: -6.750205,
    longitude: -2.52777,
    tags: ['sit', 'laborum', 'ad', 'sunt', 'exercitation', 'culpa', 'est'],
    friends: [
      {
        id: 0,
        name: 'Mavis Riley',
      },
      {
        id: 1,
        name: 'Felicia Blackburn',
      },
      {
        id: 2,
        name: 'Marilyn Harrell',
      },
    ],
    greeting: 'Hello, Cornelia Meadows! You have 2 unread messages.',
    favoriteFruit: 'banana',
  },
];
